import distutils.sysconfig as sysconfig

platform=Environment()["PLATFORM"]

pylib = sysconfig.get_config_var('LIBPL')
pyinc = sysconfig.get_config_var('INCLUDEPY')
version = sysconfig.get_config_var('VERSION')
if version==None:
    version='25'
pyver = 'python' + version

# change architecture if necessary
arch = 'prescott -msse3'

# For Python interface only
pif_conv = Split("cppvec_conv_pif.cpp cpppointer_conv_pif.cpp cppmap_conv_pif.cpp ")
pif = Split("flow_pif.cpp analyzer_pif.cpp label_pif.cpp")
filenames = ['analyzer', 'label']
files = [filename + '.cpp' for filename in filenames]
test_files = ['test_seg_fault.cpp']

if platform == 'win32':
    env = Environment(
        LIBS=['ANN', pyver],
        LIBPATH=['C:/ann_1.1.1/MS_Win32/dll/Release','C:/ann_1.1.1/MS_Win32/bin','C:/Program Files/boost/boost_1_35_0/lib'],
        CPPPATH=['C:/ann_1.1.1/include/ANN','C:/Program Files/boost/boost_1_35_0/include'],
        CXXFLAGS='-Wall -w -DANSI -EHsc /D "WIN32"',
        )

    bp = Environment(
        LIBS=['ANN', 'boost_python', pyver],
        LIBPATH=['C:/ann_1.1.1/MS_Win32/dll/Release','C:/ann_1.1.1/MS_Win32/bin','C:/Program Files/boost/boost_1_35_0/lib'],
        CPPPATH=['C:/ann_1.1.1/include/ANN','C:/Program Files/boost/boost_1_35_0/include'],
        CXXFLAGS='-Wall -w -DANSI -EHsc /GR /D "WIN32"',
        OBJSUFFIX='.objs'
        )


elif platform == 'darwin':
    # pylib = "/usr/lib/python/2.5/config"
    # pyinc = "/usr/include/python2.5"

    print platform
    print pyinc
    print pyver
    env = Environment(
        LIBS=['ANN'],
        LIBPATH=['/usr/local/src/ann_1.1.1/lib'],
        CPPPATH=['/usr/local/src/ann_1.1.1/include/ANN', '/usr/local/include/boost-1_36', pyinc],
        LINKFLAGS='-framework Python -framework Accelerate',
        CXXFLAGS='-bundle -Wall -Wno-long-long -pipe -mtune=%s' % arch,
        )


    bp = Environment(
        CPPDEFINES=['BOOST_PYTHON_DYNAMIC_LIB'],
        LIBS=['ANN', 'boost_python'],
        # LIBS=['ANN',  pyver],   
        LIBPATH=['/usr/local/src/ann_1.1.1/lib'],
        CPPPATH=['/usr/local/src/ann_1.1.1/include/ANN', '/usr/local/include/boost-1_36', pyinc],
        LINKFLAGS = '-framework Python -framework Accelerate', 
        CXXFLAGS='-bundle -Wall -Wno-long-long -pipe  -mtune=%s -fno-strict-aliasing -fPIC -no-cpp-precomp -ftemplate-depth-130 -w -DBOOST_DISABLE_THREADS' % arch,
        SHLIBPREFIX = '', # gets rid of lib prefix
        SHLIBSUFFIX = sysconfig.get_config_vars('SO')
        )

else : # works for Debian and Ubuntu
    env = Environment(
        CPPDEFINES=[],
        CPPPATH=['/usr/local/src/ann_1.1.1/include/ANN', '/usr/include/', '/usr/local/include', pyinc],
        CXXFLAGS='-Wall -Wno-long-long -pipe -O3 -ffast-math -mtune=%s' % arch,
        LIBPATH=['/usr/local/src/ann_1.1.1/lib', '/usr/lib', '/usr/local/lib'],
        LIBS=['ANN', 'm', pyver],
        )

    bp = Environment(
        CPPDEFINES=['BOOST_PYTHON_DYNAMIC_LIB '],
        CPPPATH=['/usr/local/src/ann_1.1.1/include/ANN', '/usr/include/', '/usr/local/include', pyinc],
        LIBS=['ANN', 'boost_python', pyver],
        CXXFLAGS='-Wall -Wno-long-long -pipe -O3 -ffast-math -mtune=%s -fno-strict-aliasing -fPIC -ftemplate-depth-130 -w -DBOOST_DISABLE_THREADS' % arch,
        LIBPATH=['/usr/local/src/ann_1.1.1/lib', pylib, '/usr/lib', '/usr/local/lib'], 
        SHLIBPREFIX=''
        )

# Boost python shared library.
flow = bp.SharedLibrary(target='flow', source = files + pif_conv + pif)
bp.Install('../../plugins/statistics/Kde/', flow)
bp.Alias('install', '../../plugins/statistics/Kde')

