Document: flow
Title: Debian flow Manual
Author: <insert document author here>
Abstract: This manual describes what flow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flow/flow.sgml.gz

Format: postscript
Files: /usr/share/doc/flow/flow.ps.gz

Format: text
Files: /usr/share/doc/flow/flow.text.gz

Format: HTML
Index: /usr/share/doc/flow/html/index.html
Files: /usr/share/doc/flow/html/*.html

  
